# FROM php:8.0-rc-fpm-alpine AS production

FROM php:8.0.0rc1-alpine AS development

RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

# Create app directory
ENV WORK_DIR /usr/src/app
WORKDIR ${WORK_DIR}

COPY . ./

#CMD symfony server:start -p 5000

CMD php -S 0.0.0.0:5000 -t public